

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme


title: Terrapin Finance
description: Easy Data

show_downloads: [true]                  # [true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics: G-62Q05YSKJF          # [Your Google Analytics tracking ID]
