title: Terrapin Finance
description: Easy Fixed Income Data

baseurl: ""
url: "https://adamterrapin.github.io"
theme: jekyll-theme-cayman

# Build settings
markdown: kramdown
permalink: pretty


remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

show_downloads: [true]                  # [true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics: G-62Q05YSKJF          # [Your Google Analytics tracking ID]


